steps:

  - id: deployment
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - kiki-function
      - --runtaime=go113
      - --region=us-central1
      - --source=./main
